DROP TABLE T_ELECTRONIC IF EXISTS;

CREATE TABLE t_electronic (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    power_watts DECIMAL(10, 2) NOT NULL,
    status VARCHAR(5) NOT NULL
);